[package]

name = "segimap"
version = "0.0.1"
authors = []

[[bin]]

name = "segimap"
path = "src/main.rs"

[dependencies.rust-crypto]

git = "https://github.com/DaGenix/rust-crypto"
rev = "475643257a712af8522f544ad668b620c8476612"

[dependencies.peg]

git = "https://github.com/kevinmehall/rust-peg"
rev = "8b0852d15f881b335a4281df931e527aa52322a6"

[dependencies.toml]

git = "https://github.com/alexcrichton/toml-rs"
rev = "05c1eb420f54569336b8481c28a46b5a7c51ec99"
