[package]

name = "segimap"
version = "0.0.1"
authors = []

[[bin]]

name = "segimap"
path = "src/main.rs"

[dependencies]
log = "*"
peg = "*"
rand = "*"
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
rust-crypto = "*"
time = "*"
toml = "*"
bufstream = "*"
walkdir = "*"
